# Generated by Django 4.1.6 on 2024-04-20 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("ccf22200-c881-4828-bb74-58e4613e4823"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
