# Generated by Django 4.1.6 on 2024-04-20 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("6f41c9b1-5130-4cd9-be34-0a75db62677e"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="UserRoomLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.UUID("22a91359-8ada-439c-a7b1-ab1fb9c0617d"),
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_room_link_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
