# Generated by Django 4.1.6 on 2024-04-20 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_user_id_userroomlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.UUID("cf0fc500-7656-4128-9593-db141443dae1"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userroomlink",
            name="id",
            field=models.CharField(
                default=uuid.UUID("265a270f-d38c-4fb1-bb03-44f57df8c74b"),
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterModelTable(
            name="userroomlink",
            table="user_room_link",
        ),
    ]
